web/router.ex
defmodule Slackernews.Router do
  use Slackernews.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Slackernews.Plug.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Slackernews do
    pipe_through :browser # Use the default browser stack

    get "/", PostController, :index
    get "/latest", PostController, :latest
    get "/delete/:id", PostController, :delete
    get "/submit", PostController, :new
    post "/submit", PostController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/register", RegisterController, :new
    post "/register", RegisterController, :create

  end

  # Other scopes may use custom stacks.
  # scope "/api", Slackernews do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Slackernews.LayoutView do
  use Slackernews.Web, :view

  def title do
    Slackernews.Endpoint.config(:app_name)
  end

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])
    if path == current_path do
      "active"
    else
      ""
    end
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SlackerNews <%= title %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid" role="main">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= post_path @conn, :index %>">SlackerNews</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="<%= active_class @conn, post_path(@conn, :index) %>"><%= link "Popular", to: post_path(@conn, :index) %></li>
              <li class="<%= active_class @conn, post_path(@conn, :latest) %>"><%= link "Latest", to: post_path(@conn, :latest) %></li>
              <%= if @conn.assigns.current_user do %>
              <li class="<%= active_class @conn, post_path(@conn, :new) %>"><%= link "Submit", to: post_path(@conn, :new) %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <%= if @conn.assigns.current_user do %>
                <li><a href=""><%= @conn.assigns.current_user.name %></a></li>
              <li><a href="<%= session_path @conn, :delete %>">Logout</a></li>
              <% else %>
              <li><a href="<%= session_path @conn, :new %>">Sign in</a></li>
              <li><a href="<%= register_path @conn, :new %>">Register</a></li>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>